channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=conda_forge
  - _openmp_mutex=4.5=2_gnu
  - absl-py=2.1.0=pyhd8ed1ab_0
  - anndata=0.10.8=pyhd8ed1ab_0
  - aom=3.9.1=hac33072_0
  - array-api-compat=1.8=pyhd8ed1ab_0
  - blas=1.0=mkl
  - blosc=1.21.5=hc2324a3_1
  - brotli=1.1.0=hd590300_1
  - brotli-bin=1.1.0=hd590300_1
  - brotli-python=1.0.9=py312h6a678d5_8
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.33.1=heb4867d_0
  - ca-certificates=2024.7.4=hbcca054_0
  - cached-property=1.5.2=hd8ed1ab_1
  - cached_property=1.5.2=pyha770c72_1
  - certifi=2024.7.4=pyhd8ed1ab_0
  - charset-normalizer=3.3.2=pyhd3eb1b0_0
  - chex=0.1.86=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_0
  - contextlib2=21.6.0=pyhd8ed1ab_0
  - contourpy=1.2.1=py312h8572e83_0
  - cuda-cudart=12.4.127=0
  - cuda-cupti=12.4.127=0
  - cuda-libraries=12.4.0=0
  - cuda-nvrtc=12.4.127=0
  - cuda-nvtx=12.4.127=0
  - cuda-opencl=12.6.37=0
  - cuda-runtime=12.4.0=0
  - cuda-version=12.6=3
  - cycler=0.12.1=pyhd8ed1ab_0
  - dav1d=1.2.1=hd590300_0
  - docrep=0.3.2=pyh44b312d_0
  - et_xmlfile=1.1.0=pyhd8ed1ab_0
  - etils=1.9.2=pyhd8ed1ab_0
  - exceptiongroup=1.2.2=pyhd8ed1ab_0
  - expat=2.6.2=h6a678d5_0
  - ffmpeg=4.3=hf484d3e_0
  - filelock=3.13.1=py312h06a4308_0
  - flax=0.9.0=pyhd8ed1ab_0
  - fonttools=4.53.1=py312h41a817b_0
  - freetype=2.12.1=h4a9f257_0
  - fsspec=2024.6.1=pyhff2d567_0
  - get-annotations=0.1.2=pyhd8ed1ab_0
  - gmp=6.2.1=h295c915_3
  - gnutls=3.6.15=he1e5248_0
  - h5py=3.11.0=nompi_py312hb7ab980_102
  - hdf5=1.14.3=nompi_h4f84152_101
  - idna=3.7=py312h06a4308_0
  - importlib-metadata=8.4.0=pyha770c72_0
  - importlib_metadata=8.4.0=hd8ed1ab_0
  - importlib_resources=6.4.4=pyhd8ed1ab_0
  - intel-openmp=2023.1.0=hdb19cb5_46306
  - jax=0.4.27=pyhd8ed1ab_0
  - jaxlib=0.4.23=cpu_py312h8d2594f_2
  - jinja2=3.1.4=py312h06a4308_0
  - joblib=1.4.2=pyhd8ed1ab_0
  - keyutils=1.6.1=h166bdaf_0
  - kiwisolver=1.4.5=py312h8572e83_1
  - krb5=1.21.3=h659f571_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=hb7c19ff_0
  - ld_impl_linux-64=2.38=h1181459_1
  - legacy-api-wrap=1.4=pyhd8ed1ab_1
  - lerc=4.0.0=h27087fc_0
  - libabseil=20240116.2=cxx17_he02047a_1
  - libaec=1.1.3=h59595ed_0
  - libavif16=1.1.1=h104a339_1
  - libblas=3.9.0=1_h86c2bf4_netlib
  - libbrotlicommon=1.1.0=hd590300_1
  - libbrotlidec=1.1.0=hd590300_1
  - libbrotlienc=1.1.0=hd590300_1
  - libcblas=3.9.0=6_ha36c22a_netlib
  - libcublas=12.4.2.65=0
  - libcufft=11.2.0.44=0
  - libcufile=1.11.0.15=0
  - libcurand=10.3.7.37=0
  - libcurl=8.7.1=hca28451_0
  - libcusolver=11.6.0.99=0
  - libcusparse=12.3.0.142=0
  - libdeflate=1.20=hd590300_0
  - libedit=3.1.20191231=he28a2e2_2
  - libev=4.33=hd590300_2
  - libexpat=2.6.2=h59595ed_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc=14.1.0=h77fa898_1
  - libgcc-ng=14.1.0=h69a702a_1
  - libgfortran=14.1.0=h69a702a_1
  - libgfortran-ng=14.1.0=h69a702a_1
  - libgfortran5=14.1.0=hc5f4f2c_1
  - libgomp=14.1.0=h77fa898_1
  - libgrpc=1.62.2=h15f2491_0
  - libiconv=1.16=h5eee18b_3
  - libidn2=2.3.4=h5eee18b_0
  - libjpeg-turbo=3.0.0=hd590300_1
  - liblapack=3.9.0=6_ha36c22a_netlib
  - libllvm14=14.0.6=hcd5def8_4
  - libnghttp2=1.58.0=h47da74e_1
  - libnpp=12.2.5.2=0
  - libnsl=2.0.1=hd590300_0
  - libnvfatbin=12.6.20=0
  - libnvjitlink=12.4.99=0
  - libnvjpeg=12.3.1.89=0
  - libpng=1.6.43=h2797004_0
  - libprotobuf=4.25.3=h08a7969_0
  - libre2-11=2023.09.01=h5a48ba9_2
  - libsqlite=3.46.0=hde9e2c9_0
  - libssh2=1.11.0=h0841786_0
  - libstdcxx=14.1.0=hc0a3c3a_1
  - libstdcxx-ng=14.1.0=h4852527_1
  - libtasn1=4.19.0=h5eee18b_0
  - libtiff=4.6.0=h1dd3fc0_3
  - libunistring=0.9.10=h27cfd23_0
  - libuuid=2.38.1=h0b41bf4_0
  - libwebp-base=1.3.2=h5eee18b_0
  - libxcb=1.15=h0b41bf4_0
  - libxcrypt=4.4.36=hd590300_1
  - libzlib=1.2.13=h4ab18f5_6
  - lightning=2.4.0=pyhd8ed1ab_0
  - lightning-utilities=0.11.6=pyhd8ed1ab_0
  - llvm-openmp=14.0.6=h9e868ea_0
  - llvmlite=0.43.0=py312h6a678d5_0
  - lz4-c=1.9.4=h6a678d5_1
  - markdown-it-py=3.0.0=pyhd8ed1ab_0
  - markupsafe=2.1.3=py312h5eee18b_0
  - matplotlib-base=3.9.2=py312h854627b_0
  - mdurl=0.1.2=pyhd8ed1ab_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py312h5eee18b_1
  - mkl_fft=1.3.8=py312h5eee18b_0
  - mkl_random=1.2.4=py312hdb19cb5_0
  - ml-collections=0.1.1=pyhd8ed1ab_0
  - ml_dtypes=0.4.0=py312h1d6d2e6_1
  - mpmath=1.3.0=py312h06a4308_0
  - msgpack-python=1.0.8=py312h2492b07_0
  - mudata=0.3.0=pyhd8ed1ab_0
  - multipledispatch=0.6.0=pyhd8ed1ab_1
  - munkres=1.1.4=pyh9f0ad1d_0
  - natsort=8.4.0=pyhd8ed1ab_0
  - ncurses=6.4=h6a678d5_0
  - nest-asyncio=1.6.0=pyhd8ed1ab_0
  - nettle=3.7.3=hbbd107a_1
  - networkx=3.3=py312h06a4308_0
  - numba=0.60.0=py312h83e6fd3_0
  - numpy=1.26.4=py312hc5e2394_0
  - numpy-base=1.26.4=py312h0da6c21_0
  - numpyro=0.15.2=pyhd8ed1ab_0
  - openh264=2.1.1=h4ff587b_0
  - openjpeg=2.5.2=he7f1fd0_0
  - openpyxl=3.1.5=py312h98912ed_0
  - openssl=3.3.1=hb9d3cd8_3
  - opt-einsum=3.3.0=hd8ed1ab_2
  - opt_einsum=3.3.0=pyhc1e730c_2
  - optax=0.2.2=pyhd8ed1ab_1
  - orbax-checkpoint=0.4.4=pyhd8ed1ab_0
  - packaging=24.1=pyhd8ed1ab_0
  - pandas=2.2.2=py312h1d6d2e6_1
  - patsy=0.5.6=pyhd8ed1ab_0
  - pillow=10.3.0=py312hdcec9eb_0
  - pip=24.2=py312h06a4308_0
  - protobuf=4.25.3=py312h72fbbdf_0
  - pthread-stubs=0.4=h36c2ea0_1001
  - pybind11-abi=4=hd8ed1ab_3
  - pygments=2.18.0=pyhd8ed1ab_0
  - pynndescent=0.5.13=pyhff2d567_0
  - pyparsing=3.1.4=pyhd8ed1ab_0
  - pyro-api=0.1.2=pyhd8ed1ab_0
  - pyro-ppl=1.9.1=pyhd8ed1ab_0
  - pysocks=1.7.1=py312h06a4308_0
  - python=3.12.2=hab00c5b_0_cpython
  - python-dateutil=2.9.0=pyhd8ed1ab_0
  - python-tzdata=2024.1=pyhd8ed1ab_0
  - python_abi=3.12=5_cp312
  - pytorch=2.4.0=py3.12_cuda12.4_cudnn9.1.0_0
  - pytorch-cuda=12.4=hc786d27_6
  - pytorch-lightning=2.4.0=pyhd8ed1ab_0
  - pytorch-mutex=1.0=cuda
  - pytz=2024.1=pyhd8ed1ab_0
  - pyyaml=6.0.1=py312h5eee18b_0
  - qhull=2020.2=h434a139_5
  - rav1e=0.6.6=he8a937b_2
  - re2=2023.09.01=h7f4b329_2
  - readline=8.2=h5eee18b_0
  - requests=2.32.3=py312h06a4308_0
  - rich=13.7.1=pyhd8ed1ab_0
  - scanpy=1.10.2=pyhd8ed1ab_0
  - scikit-learn=1.5.1=py312h775a589_0
  - scipy=1.14.1=py312h7d485d2_0
  - scvi-tools=1.1.6=pyhd8ed1ab_1
  - seaborn=0.13.2=hd8ed1ab_2
  - seaborn-base=0.13.2=pyhd8ed1ab_2
  - session-info=1.0.0=pyhd8ed1ab_0
  - setuptools=72.1.0=py312h06a4308_0
  - six=1.16.0=pyh6c4a22f_0
  - snappy=1.2.1=ha2e4443_0
  - sparse=0.15.4=pyhd8ed1ab_0
  - sqlite=3.45.3=h5eee18b_0
  - statsmodels=0.14.2=py312h085067d_0
  - stdlib-list=0.10.0=pyhd8ed1ab_0
  - svt-av1=2.2.1=h5888daf_0
  - sympy=1.12=py312h06a4308_0
  - tbb=2021.8.0=hdb19cb5_0
  - tensorstore=0.1.59=py312hf74fac6_0
  - threadpoolctl=3.5.0=pyhc1e730c_0
  - tk=8.6.14=h39e8969_0
  - toolz=0.12.1=pyhd8ed1ab_0
  - torchaudio=2.4.0=py312_cu124
  - torchmetrics=1.4.0.post0=pyhd8ed1ab_0
  - torchtriton=3.0.0=py312
  - torchvision=0.19.0=py312_cu124
  - tqdm=4.66.5=pyhd8ed1ab_0
  - typing-extensions=4.11.0=py312h06a4308_0
  - typing_extensions=4.11.0=py312h06a4308_0
  - tzdata=2024a=h04d1e81_0
  - umap-learn=0.5.6=py312h7900ff3_1
  - urllib3=2.2.2=py312h06a4308_0
  - wheel=0.43.0=py312h06a4308_0
  - xarray=2024.7.0=pyhd8ed1ab_0
  - xorg-libxau=1.0.11=hd590300_0
  - xorg-libxdmcp=1.1.3=h7f98852_0
  - xz=5.4.6=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zipp=3.20.1=pyhd8ed1ab_0
  - zlib=1.2.13=h4ab18f5_6
  - zstd=1.5.5=hc292b87_2
